services:
  odoo-notifier:
    build: .
    restart: always
    env_file:
      - src/.env  # Apuntamos a la ubicación real de tu .env
    volumes:
      - ./data:/app/data  # Esto creará una carpeta 'data' en tu raíz para el last_id.txt
